Part 1: Gaussian Elimination without Row Swapping

In [29]:
from numpy import *
import numpy as np
import time
import matplotlib.pyplot as plt
%matplotlib inline

In [30]:
# Matrix and Vector from HW2, task 2
matr = np.array([[-3., 2., -1.], [6., -6., 7.], [3., -4., 4.]])
vect = np.array([-1., -7., -6.])

matr_rows = shape(matr)[0]
#print(matr_rows)
matr_columns = shape(matr)[1]
#print(matr_columns) 

# looping trhough matrix rows 
for r in range (1, matr_rows):
  
  # looping through matrix rows
  for i in range (r, matr_rows):
    ll = matr[i,r-1] / matr[r-1,r-1] 
        
    # looping through columns, x1 .. xn and b
    for j in range (r-1, matr_columns):
        matr[i,j] = matr[i,j] - matr[r-1, j] * ll

    vect[i] = vect[i] - vect[r-1] * ll    
    
    print(matr)
    print(vect)
    print('-----')

  print('-- -- -- --')

[[-3.  2. -1.]
 [ 0. -2.  5.]
 [ 3. -4.  4.]]
[-1. -9. -6.]
-----
[[-3.  2. -1.]
 [ 0. -2.  5.]
 [ 0. -2.  3.]]
[-1. -9. -7.]
-----
-- -- -- --
[[-3.  2. -1.]
 [ 0. -2.  5.]
 [ 0.  0. -2.]]
[-1. -9.  2.]
-----
-- -- -- --


In [31]:
# Backward Substitution
print(matr)
print(shape(matr))
print(vect)
print(shape(vect))

n = shape(matr)[0]
x = np.zeros(n)

n = n - 1   # Python starts from 0
print('n =', n)
print(shape(x))

x[n] = vect[n] / matr[n,n]   # last element in the vector x[]
print('x[%d] = %d' % (n, x[n]) )
print('-----')

# first number of the range is included, last number is not
for i in reversed(range(0, n) ):
    s = vect[i]
    #print('vect[%d] = %d' % (i, s) ) 

    for j in range (i, n+1):
        #print('j =', j)
        s = s - matr[i, j] * x[j]   
    x[i] = s / matr[i, i]
    print('x[%d] = %d' % (i, x[i]) )
    
print('Solution matrix:')
print(x)

[[-3.  2. -1.]
 [ 0. -2.  5.]
 [ 0.  0. -2.]]
(3, 3)
[-1. -9.  2.]
(3,)
n = 2
(3,)
x[2] = -1
-----
x[1] = 2
x[0] = 2
Solution matrix:
[ 2.  2. -1.]
